apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qjde
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0006-tenant/ci10t-776-0006-app/devfile-sample-qjde@sha256:bec6ef450a02e99a3d1d55697a1eeb6abacdfc645c68a09aadcb9363ebc104df
        name: my-nodejs
        resources: {}
status: {}
